# data & columns
data_path: "data/processed/baseline_dataset.parquet"  # .csv тоже поддерживается
target: "churned"
id_cols: []                     # допустимо пустое
numeric_features: []            # опционально, оставить пустым чтобы инферить
categorical_features: []        # опционально, оставить пустым чтобы инферить

# model
model:
  name: "rf"   # варианты: logreg, rf
  params:
    #C: 1.0
    #penalty: "l2"
    #class_weight: null   # или "balanced"

# train & eval
test_size: 0.2
random_state: 42
output_dir: "artifacts/baseline"
cv:
  n_splits: 5

# MLflow (опционально)
mlflow:
  enabled: true
  tracking_uri: "file:./mlruns"   # или http(s)://... для сервера
  experiment: "olist_baseline_cli"
  run_name: "baseline_rf"
  autolog: true                  # в fit() включит mlflow.sklearn.autolog
  log_model: true                # логировать sklearn-пайплайн как модель